services:
  redis:
    image: redis:7-alpine
    container_name: yara_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:16-alpine
    container_name: yara_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: yara_db
      POSTGRES_USER: yara_user
      POSTGRES_PASSWORD: yara_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yara_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: yara_redis_commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  pgdata:
  redisdata:
